### ISSUE TITLE
AttributeError: _parse_flags

### ISSUE THREAD

**Issue by tinnarey** [DouYishun/KB-QA#2]
您好 我在运行您的代码的时候遇到了这个报错，
Traceback (most recent call last):
  File "C:/film/KB-QA-master/train.py", line 54, in <module>
    FLAGS._parse_flags()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\flags\_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags

win7  Python3.6    请问您知道是什么原因吗

**Comment by SeekPoint** [comment]
I got the same error, how to fix it?

**Comment by tinnarey** [comment]
把他注释掉就好了 我感觉是因为Python3.6对应的TensorFlow没有这个函数

**Comment by MrRace** [comment]
ft版本的原因，可以试试替换为FLAGS._parse_flags()
