### ISSUE TITLE
InternalError (see above for traceback): cudnn PoolBackward launch failed

### ISSUE THREAD

**Issue by yanqiangmiffy** [DouYishun/KB-QA#5]
```
2018-05-11 17:10:33.510303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
Writing to /root/yanqiang/KB-QA/runs/1526029896

2018-05-11 17:12:01.109717: E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 7102 (compatibil.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile co
2018-05-11 17:12:01.110291: W ./tensorflow/stream_executor/stream.h:1988] attempting to perform DNN operation using StreamExe
2018-05-11 17:12:01.111674: E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 7102 (compatibil.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile co
2018-05-11 17:12:01.112370: W ./tensorflow/stream_executor/stream.h:1988] attempting to perform DNN operation using StreamExe
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __e
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: cudnn PoolBackward launch failed
	 [[Node: gradients/LSTM_scope_1/MaxPool_grad/MaxPoolGrad = MaxPoolGrad[T=DT_FLOAT, data_format="NHWC", ksize=[1, 100,ool, gradients/LSTM_scope_1/Reshape_grad/Reshape)]]
	 [[Node: GradientDescent_1/update_LSTM_scope/bidirectional_rnn/fw/basic_lstm_cell/bias/ApplyGradientDescent/_66 = _Re", send_device_incarnation=1, tensor_name="edge_114789_GradientDescent_1/update_LSTM_scope/bidirectional_rnn/fw/basic_lstm_ce

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 217, in <module>
    lstm.falseCosSim, lstm.loss, summary_op], feed_dict)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: cudnn PoolBackward launch failed
	 [[Node: gradients/LSTM_scope_1/MaxPool_grad/MaxPoolGrad = MaxPoolGrad[T=DT_FLOAT, data_format="NHWC", ksize=[1, 100,ool, gradients/LSTM_scope_1/Reshape_grad/Reshape)]]
	 [[Node: GradientDescent_1/update_LSTM_scope/bidirectional_rnn/fw/basic_lstm_cell/bias/ApplyGradientDescent/_66 = _Re", send_device_incarnation=1, tensor_name="edge_114789_GradientDescent_1/update_LSTM_scope/bidirectional_rnn/fw/basic_lstm_ce

Caused by op 'gradients/LSTM_scope_1/MaxPool_grad/MaxPoolGrad', defined at:
  File "train.py", line 144, in <module>
    tf.gradients(lstm.loss, tvars), FLAGS.max_grad_norm)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 609, in gradie
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 375, in _Maybe
    return grad_fn()  # Exit early
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 609, in <lambd
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/ops/nn_grad.py", line 583, in _MaxPoolGrad
    data_format=op.get_attr("data_format"))
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 3291, in _max_pool
    data_format=data_format, name=name)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in 
    op_def=op_def)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'LSTM_scope_1/MaxPool', defined at:
  File "train.py", line 138, in <module>
    FLAGS.margin
  File "/root/yanqiang/KB-QA/biLSTM.py", line 35, in __init__
    true_answer2 = tf.nn.tanh(self.max_pooling(true_answer1))
  File "/root/yanqiang/KB-QA/biLSTM.py", line 77, in max_pooling
    output = tf.nn.max_pool(lstm_out, ksize=[1, height, 1, 1], strides=[1, 1, 1, 1], padding='VALID')
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 2043, in max_pool
    name=name)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 3018, in _max_pool
    data_format=data_format, name=name)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in 
    op_def=op_def)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/root/.pyenv/versions/3.5.3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): cudnn PoolBackward launch failed
	 [[Node: gradients/LSTM_scope_1/MaxPool_grad/MaxPoolGrad = MaxPoolGrad[T=DT_FLOAT, data_format="NHWC", ksize=[1, 100,ool, gradients/LSTM_scope_1/Reshape_grad/Reshape)]]
	 [[Node: GradientDescent_1/update_LSTM_scope/bidirectional_rnn/fw/basic_lstm_cell/bias/ApplyGradientDescent/_66 = _Re", send_device_incarnation=1, tensor_name="edge_114789_GradientDescent_1/update_LSTM_scope/bidirectional_rnn/fw/basic_lstm_ce


```

**Comment by yanqiangmiffy** [comment]
老师，下面是我的运行环境，本来报了`GPU OOM`错误，我把batch_size改小了，然后报了`cudnn PoolBackward launch failed `
- tensorflow 1.5.1
- Python 3.6
- CUDA 9.0
- GPU: GeForce GTX 1050
- OS：Linux
- cuDNN ：7.1.2

**Comment by yanqiangmiffy** [comment]
更新tensorflow到最新版本

**Comment by yanqiangmiffy** [comment]
```
# training parameters
tf.flags.DEFINE_integer("batch_size", 256, "Batch Size (default: 64)")
```
老师，您好，因为由于内存不足，我把256改成了64，但是最终测试集预测结果为44%左右，请问下改动这个有没有影响结果

**Comment by Yishun99** [comment]
这个数据大概也就能到这个准确率(我和几个同学的结果大概都这样)... 
just a KB-QA example

**Comment by yanqiangmiffy** [comment]
I get it！ 
多谢了
