### ISSUE TITLE
运行时找不到文件dictionary.dict

### ISSUE THREAD

**Issue by andybilly** [DouYishun/KB-QA#6]
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    train_sim_ixs = similarity.topk_sim_ix(FLAGS.knowledge_file, FLAGS.train_file, stop_words, FLAGS.k)
  File "/home/andybily/pytorch_program/KB-QA-master/similarity.py", line 30, in topk_sim_ix
    generate_dic_and_corpus(knowledge_file, file_name, stop_words)
  File "/home/andybily/pytorch_program/KB-QA-master/similarity.py", line 15, in generate_dic_and_corpus
    dictionary.save(os.path.join('tmp/dictionary.dict'))
  File "/usr/local/lib/python3.5/dist-packages/gensim/utils.py", line 682, in save
    self._smart_save(fname_or_handle, separately, sep_limit, ignore, pickle_protocol=pickle_protocol)
  File "/usr/local/lib/python3.5/dist-packages/gensim/utils.py", line 538, in _smart_save
    pickle(self, fname, protocol=pickle_protocol)
  File "/usr/local/lib/python3.5/dist-packages/gensim/utils.py", line 1337, in pickle
    with smart_open(fname, 'wb') as fout:  # 'b' for binary, needed on Windows
  File "/usr/local/lib/python3.5/dist-packages/smart_open/smart_open_lib.py", line 181, in smart_open
    fobj = _shortcut_open(uri, mode, **kw)
  File "/usr/local/lib/python3.5/dist-packages/smart_open/smart_open_lib.py", line 287, in _shortcut_open
    return io.open(parsed_uri.uri_path, mode, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/dictionary.dict'

**Comment by yuewang1402** [comment]
你好，我也遇到了同样的问题。
请问你找到方法解决了吗？
谢谢。

**Comment by LittleBenXi** [comment]
我也遇到了这个问题，请问怎么解决的

**Comment by LittleBenXi** [comment]
貌似在当前目录下新建个tmp/dictionary.dict，就可以了
